#Use one of below  values to run automation in different environments, please configure one of below values for "environment" in line 24
browser.required=true
browser.type=chrome
browser.headless=true

environment=India


